# Generated by Django 4.1.3 on 2022-11-06 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user',
            new_name='name',
        ),
    ]
