# Generated by Django 4.1.3 on 2022-11-06 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_user_contact_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='current_user',
        ),
    ]
