# Generated by Django 4.1.3 on 2022-11-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genpass',
            name='date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='genpass',
            name='passwords',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='genpass',
            name='site',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
