# Generated by Django 4.1.3 on 2022-11-12 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/img_profil/default.jpg', upload_to='user/media/img_profil/'),
        ),
    ]
