# Generated by Django 4.1.3 on 2022-11-05 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_delete_mdpgenere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_list',
        ),
    ]
